
"""Create todo table

Revision ID: fd95913d8aee
Revises: e0f3f4958720
Create Date: 2025-09-09 12:49:58.171723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fd95913d8aee' # <-- Important: Use the ID from your filename
down_revision: Union[str, Sequence[str], None] = 'e0f3f4958720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_title'), 'todo', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_title'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###

"""Create todo table

Revision ID: fd95913d8aee
Revises: d983381ebb3c
Create Date: 2025-09-09 12:49:58.171723

"""

'fd95913d8aee'